@url_dev=http://localhost:8080/v1/api/
### signup

POST {{url_dev}}/shop/signup
Content-Type: application/json

{
    "name": "Shop TIPS",
    "email": "shoptipjs5@gmail.com",
    "password": "abc123"
}